/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Meryem
 */
public class Gender extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Gender() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWoman = new javax.swing.JButton();
        lblSelectGender = new javax.swing.JLabel();
        btnMan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnWoman.setText("WOMAN");
        btnWoman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWomanActionPerformed(evt);
            }
        });
        getContentPane().add(btnWoman, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 140, 40));

        lblSelectGender.setBackground(new java.awt.Color(102, 255, 255));
        lblSelectGender.setText("PLEASE SELECT YOUR GENDER");
        getContentPane().add(lblSelectGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 220, 40));

        btnMan.setText("MAN");
        btnMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManActionPerformed(evt);
            }
        });
        getContentPane().add(btnMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 183, 130, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/9907-2_S_-600x600.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWomanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWomanActionPerformed
        Woman woman = new Woman();
        woman.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnWomanActionPerformed

    private void btnManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManActionPerformed
        Man man = new Man();
        man.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnManActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMan;
    private javax.swing.JButton btnWoman;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblSelectGender;
    // End of variables declaration//GEN-END:variables
}
