
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Meryem
 */
public class ShoppingCart extends javax.swing.JFrame implements DataTransfer{
private static List<Object[]> recordedData = new ArrayList<>();
 

    /**
     * Creates new form ShoppingCart
     */
    public ShoppingCart() {
        initComponents();
       
    

    
    
    
}
private void updateTable() {
    DefaultTableModel model = (DefaultTableModel) tblTotal.getModel();
    model.setRowCount(0); 
    for (Object[] satir : recordedData) {
        model.addRow(satir);
    }
}
    public void sendData(List<Object[]> veriler) {
        DefaultTableModel model = (DefaultTableModel) tblTotal.getModel();
        model.setRowCount(0); 
        for (Object[] satir : veriler) {
            model.addRow(satir);
        }
        recordedData.addAll(veriler);
        updateTable();
    }
    

    @Override
    public List<Object[]> getData() {
        
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTotal = new javax.swing.JTable();
        btnBackS = new javax.swing.JButton();
        btnCompleteShopping = new javax.swing.JButton();
        txtComplete = new javax.swing.JTextField();
        txtTotalAmount = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        lblPİC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmShopping"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("SELECTED PRODUCTS ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 130, -1));

        tblTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Gender", "Category", "Product_name", "Size", "Shoe_size", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTotal);
        if (tblTotal.getColumnModel().getColumnCount() > 0) {
            tblTotal.getColumnModel().getColumn(0).setResizable(false);
            tblTotal.getColumnModel().getColumn(1).setResizable(false);
            tblTotal.getColumnModel().getColumn(2).setResizable(false);
            tblTotal.getColumnModel().getColumn(3).setResizable(false);
            tblTotal.getColumnModel().getColumn(4).setResizable(false);
            tblTotal.getColumnModel().getColumn(5).setResizable(false);
            tblTotal.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 60, 470, 170));

        btnBackS.setText("BACK");
        btnBackS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackSActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 403, 110, 40));

        btnCompleteShopping.setText("COMPLETE YOUR SHOPPİNG");
        btnCompleteShopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteShoppingActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompleteShopping, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 200, 40));
        getContentPane().add(txtComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 170, 40));

        txtTotalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAmountActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 120, 100));

        btnTotal.setText("TOTAL AMOUNT");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
        getContentPane().add(btnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 130, -1));

        lblPİC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/9907-2_S_-600x600.jpg"))); // NOI18N
        getContentPane().add(lblPİC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackSActionPerformed
        Gender gender = new Gender ();
        gender.setVisible(true);
        this.setVisible(false);
        updateTable();
    }//GEN-LAST:event_btnBackSActionPerformed

    private void btnCompleteShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteShoppingActionPerformed
        txtComplete.setText("Your order has been received");
    }//GEN-LAST:event_btnCompleteShoppingActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double total = 0;
DefaultTableModel model = (DefaultTableModel) tblTotal.getModel();
int rowCount = model.getRowCount();

for (int i = 0; i < rowCount; i++) {
    try {
        Object wageData = model.getValueAt(i, 6); 
        double price = Double.parseDouble(wageData.toString());
        total += price;
    } catch (NumberFormatException e) {
        
        System.err.println("Failed " + model.getValueAt(i, 6));
    }
}
        txtTotalAmount.setText(String.valueOf(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void txtTotalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAmountActionPerformed

    }//GEN-LAST:event_txtTotalAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoppingCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShoppingCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackS;
    private javax.swing.JButton btnCompleteShopping;
    private javax.swing.JButton btnTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPİC;
    private javax.swing.JTable tblTotal;
    private javax.swing.JTextField txtComplete;
    private javax.swing.JTextField txtTotalAmount;
    // End of variables declaration//GEN-END:variables

   
 
    
}
